version: "3"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      - "RABBITMQ_DEFAULT_USER=geo"
      - "RABBITMQ_DEFAULT_PASS=geo"
      - "RABBITMQ_DEFAULT_VHOST=/"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "storage-rabbitmq:/var/lib/rabbitmq"

  geoservice:
    image: "geoservice"
    depends_on:
      - "rabbitmq"
    environment:
      - "DISPLAY::1"
    volumes:
      - "../params.py:/opt/geoservice/params.py"

volumes:
  storage-rabbitmq:

